export const ENTITIES = {
  DASHBOARD: "Dashboard",
  LOGIN: "Login",
  VGM_MENU: "VGMMenu",
  WEIGH_VGM: "WeighVGM",
  VGM_DECLARATION_FORM: "VGMDeclarationForm",
  WEIGHING_COMPANY_PROFILE: "WeighingCompanyProfile",
  TARIFF_SETUP_MENU: "TariffSetup",
  CATEGORY: "Category",
  SERVICE: "Service",
  SERVICE_CATEGORY_MAPPING: "ServiceCategoryMapping",
  TRUCK_TYPE: "TruckType",
  TARIFF: "Tariff",
  TARIFF_DETAIL: "TariffDetail",
  CUSTOMER: "Customer",
  WEIGH_GATE_IN_OUT: "WeighGateInOut",
  PERMISSION: "Permission",
  SETTING_MENU: "Setting",
  SETUP: "Setup",
  USER: "User",
};
